import { prefersReducedMotion } from '../utils/motion.js';

/**
 * Starfield - The real night sky: Yale Bright Star Catalog stars over the ESO/S. Brunier Milky Way panorama.
 * Assets are generated by scripts/build-sky.mjs.
 *
 * The sky is drawn at infinity (camera translation is ignored), so zooming moves the Earth but never the stars.
 */

// Galactic coordinates (degrees) at the centre of the view, and how far the galactic plane is turned from horizontal.
// Looking just west of the Galactic centre lets the bright core glow out from behind the Earth.
const VIEW_GALACTIC_LONGITUDE = -8;
const VIEW_GALACTIC_LATITUDE = -2;
const BAND_TILT = 55;

// Maximum mouse parallax in degrees per layer; the nearer stars move further than the Milky Way behind them.
// The difference also slides the catalogue stars off their counterparts in the photograph, so keep it small.
const PARALLAX_MILKY_WAY = 1.0;
const PARALLAX_STARS = 1.5;
// How quickly the layers follow the mouse (1/s)
const PARALLAX_FOLLOW = 3;

// J2000 galactic to equatorial rotation (transpose of the IAU equatorial to galactic matrix)
const GALACTIC_TO_EQUATORIAL = [
    [-0.0548755604, 0.4941094279, -0.8676661490],
    [-0.8734370902, -0.4448296300, -0.1980763734],
    [-0.4838350155, 0.7469822445, 0.4559837762]
];

// Projects a direction onto a sphere around the camera; 100 sits safely between the near and far planes
const SKY_VERTEX_PROJECTION = `
    vec4 skyClipPosition(vec3 direction) {
        vec3 viewDirection = normalize(mat3(viewMatrix) * mat3(modelMatrix) * direction);
        return projectionMatrix * vec4(viewDirection * 100.0, 1.0);
    }
`;

export class Starfield {
    scene: any;
    THREE: any;
    sky: any;
    milkyWay: any;
    stars: any;
    starMaterial: any;
    orientation: any;
    pointer: { x: number; y: number };
    parallax: { x: number; y: number };
    lastUpdate: number;
    onPointerMove: (event: PointerEvent) => void;

    constructor(scene: any, THREE: any) {
        this.scene = scene;
        this.THREE = THREE;
        this.milkyWay = null;
        this.stars = null;
        this.starMaterial = null;
        this.orientation = this.viewOrientation();
        this.pointer = { x: 0, y: 0 };
        this.parallax = { x: 0, y: 0 };
        this.lastUpdate = performance.now();

        this.sky = new THREE.Group();
        this.scene.add(this.sky);

        this.onPointerMove = (event: PointerEvent) => {
            if (event.pointerType !== 'mouse') return;
            this.pointer.x = event.clientX / window.innerWidth * 2 - 1;
            this.pointer.y = event.clientY / window.innerHeight * 2 - 1;
        };
        if (!prefersReducedMotion()) window.addEventListener('pointermove', this.onPointerMove);

        this.createMilkyWay();
        this.loadStars();
    }

    /** Sky frame direction (+Y = north celestial pole, +X = RA 0h, RA towards -Z) of a galactic position */
    galacticDirection(longitude: number, latitude: number) {
        const l = longitude * Math.PI / 180;
        const b = latitude * Math.PI / 180;
        const g = [Math.cos(b) * Math.cos(l), Math.cos(b) * Math.sin(l), Math.sin(b)];
        const [x, y, z] = GALACTIC_TO_EQUATORIAL.map(row => row[0] * g[0] + row[1] * g[1] + row[2] * g[2]);
        return new this.THREE.Vector3(x, z, -y);
    }

    /** Rotation that puts the configured galactic position in front of the camera with the band at BAND_TILT */
    viewOrientation() {
        const THREE = this.THREE;
        const target = this.galacticDirection(VIEW_GALACTIC_LONGITUDE, VIEW_GALACTIC_LATITUDE);
        const pole = this.galacticDirection(0, 90);
        const up = pole.sub(target.clone().multiplyScalar(pole.dot(target))).normalize();

        const tilt = BAND_TILT * Math.PI / 180;
        const forward = new THREE.Vector3(0, 0, -1);
        const screenUp = new THREE.Vector3(-Math.sin(tilt), Math.cos(tilt), 0);

        const sky = new THREE.Matrix4().makeBasis(target, up, target.clone().cross(up));
        const view = new THREE.Matrix4().makeBasis(forward, screenUp, forward.clone().cross(screenUp));
        return new THREE.Quaternion().setFromRotationMatrix(view.multiply(sky.transpose()));
    }

    createMilkyWay() {
        const THREE = this.THREE;
        const texture = new THREE.TextureLoader().load('textures/sky/milkyway.webp');
        texture.colorSpace = THREE.SRGBColorSpace;
        texture.wrapS = THREE.RepeatWrapping;
        // The view (nearly) always magnifies the map, and mipmaps would show a seam where the RA lookup wraps
        texture.generateMipmaps = false;
        texture.minFilter = THREE.LinearFilter;
        texture.magFilter = THREE.LinearFilter;

        const material = new THREE.ShaderMaterial({
            uniforms: {
                uMap: { value: texture },
                uIntensity: { value: 0.45 },
                // Pulls the photograph's sky background (residual airglow) down to black
                uBlackPoint: { value: 0.005 }
            },
            vertexShader: `
                varying vec3 vDirection;
                ${SKY_VERTEX_PROJECTION}

                void main() {
                    vDirection = position;
                    gl_Position = skyClipPosition(position);
                }
            `,
            fragmentShader: `
                #include <common>
                uniform sampler2D uMap;
                uniform float uIntensity;
                uniform float uBlackPoint;
                varying vec3 vDirection;
                #include <dithering_pars_fragment>

                void main() {
                    vec3 d = normalize(vDirection);
                    float ra = atan(-d.z, d.x);
                    float dec = asin(clamp(d.y, -1.0, 1.0));
                    vec2 uv = vec2(fract(0.5 - ra / (2.0 * PI)), 0.5 + dec / PI);

                    vec3 glow = max(texture2D(uMap, uv).rgb - uBlackPoint, 0.0) / (1.0 - uBlackPoint);
                    gl_FragColor = vec4(glow * uIntensity, 1.0);
                    #include <colorspace_fragment>
                    #include <dithering_fragment>
                }
            `,
            side: THREE.BackSide,
            depthTest: false,
            depthWrite: false,
            dithering: true
        });

        this.milkyWay = new THREE.Mesh(new THREE.SphereGeometry(1, 64, 32), material);
        this.milkyWay.renderOrder = -2;
        this.milkyWay.frustumCulled = false;
        this.sky.add(this.milkyWay);
    }

    loadStars() {
        const loader = new this.THREE.FileLoader();
        loader.setResponseType('arraybuffer');
        loader.load(
            'textures/sky/stars.bin',
            (buffer: ArrayBuffer) => this.createStars(buffer),
            undefined,
            (error: unknown) => console.error('Failed to load star catalogue', error)
        );
    }

    /**
     * Layout (see scripts/build-sky.mjs): uint32 count | int16[3n] direction | uint8[n] (V + 2) * 20 | uint8[3n] linear RGB
     */
    createStars(buffer: ArrayBuffer) {
        const THREE = this.THREE;
        const count = new Uint32Array(buffer, 0, 1)[0];
        const directions = new Int16Array(buffer, 4, count * 3);
        const encodedMags = new Uint8Array(buffer, 4 + count * 6, count);
        const colors = new Uint8Array(buffer, 4 + count * 7, count * 3);

        const magnitudes = new Float32Array(count);
        for (let i = 0; i < count; i++) magnitudes[i] = encodedMags[i] / 20 - 2;

        const geometry = new THREE.BufferGeometry();
        geometry.setAttribute('position', new THREE.BufferAttribute(directions, 3, true));
        geometry.setAttribute('aMagnitude', new THREE.BufferAttribute(magnitudes, 1));
        geometry.setAttribute('aColor', new THREE.BufferAttribute(colors, 3, true));

        this.starMaterial = new THREE.ShaderMaterial({
            uniforms: {
                uPixelRatio: { value: 1 },
                // Flux of a magnitude 6.5 star, roughly the naked-eye limit
                uExposure: { value: 0.12 },
                // Gaussian point spread in CSS pixels
                uSigma: { value: 0.65 },
                uGlare: { value: 0.006 },
                uGlareRadius: { value: 2.0 },
                uSaturation: { value: 0.7 },
                uTime: { value: 0 },
                // Peak brightness swing of the pulsing stars
                uPulse: { value: prefersReducedMotion() ? 0 : 0.18 }
            },
            vertexShader: `
                uniform float uTime;
                uniform float uPulse;
                uniform float uPixelRatio;
                uniform float uExposure;
                uniform float uSigma;
                uniform float uGlare;
                uniform float uGlareRadius;
                uniform float uSaturation;
                attribute float aMagnitude;
                attribute vec3 aColor;
                varying vec3 vColor;
                varying float vPeak;
                varying float vGlare;
                varying float vRadius;
                ${SKY_VERTEX_PROJECTION}

                void main() {
                    gl_Position = skyClipPosition(position);

                    float flux = uExposure * pow(10.0, -0.4 * (aMagnitude - 6.5));

                    // About one star in five breathes slowly (periods of 10-25 s), each with its own phase
                    float seed = fract(sin(dot(position, vec3(12.9898, 78.233, 37.719))) * 43758.5453);
                    if (seed < 0.2) {
                        float speed = 6.2831853 / mix(10.0, 25.0, fract(seed * 97.0));
                        float phase = fract(seed * 7919.0) * 6.2831853;
                        flux *= 1.0 + uPulse * mix(0.4, 1.0, fract(seed * 331.0)) * sin(uTime * speed + phase);
                    }
                    vPeak = flux / (6.2831853 * uSigma * uSigma);
                    vGlare = flux * uGlare;

                    // Radius where the core and the glare fade below one 8-bit step
                    float coreRadius = uSigma * sqrt(2.0 * log(max(vPeak * 255.0, 1.0)));
                    float glareRadius = uGlareRadius * sqrt(max(pow(vGlare * 255.0, 0.8) - 1.0, 0.0));
                    vRadius = clamp(max(coreRadius, glareRadius) + 0.5, 1.5, 32.0);
                    gl_PointSize = 2.0 * vRadius * uPixelRatio;

                    // Photometric magnitudes describe luminance, so keep it constant across colours
                    vec3 color = mix(vec3(dot(aColor, vec3(0.2126, 0.7152, 0.0722))), aColor, uSaturation);
                    vColor = color / dot(color, vec3(0.2126, 0.7152, 0.0722));
                }
            `,
            fragmentShader: `
                uniform float uSigma;
                uniform float uGlareRadius;
                varying vec3 vColor;
                varying float vPeak;
                varying float vGlare;
                varying float vRadius;

                void main() {
                    float r = length(gl_PointCoord - 0.5) * 2.0 * vRadius;

                    float core = vPeak * exp(-r * r / (2.0 * uSigma * uSigma));
                    float q = r / uGlareRadius;
                    // Scattered light falls off slower than the core, which is what makes bright stars read as bright
                    float glare = vGlare * pow(1.0 + q * q, -1.25) * (1.0 - smoothstep(0.6 * vRadius, vRadius, r));
                    core *= 1.0 - smoothstep(vRadius - 1.0, vRadius, r);

                    gl_FragColor = vec4(min(vColor * (core + glare), vec3(1.0)), 1.0);
                    #include <colorspace_fragment>
                }
            `,
            blending: THREE.AdditiveBlending,
            depthTest: false,
            depthWrite: false
        });

        this.stars = new THREE.Points(geometry, this.starMaterial);
        this.stars.renderOrder = -1;
        this.stars.frustumCulled = false;
        this.sky.add(this.stars);
    }

    /**
     * Update starfield animation
     * @param parallaxActive whether the layers should follow the mouse (only on the unscrolled start view)
     */
    update(parallaxActive = false) {
        const now = performance.now();
        const dt = Math.min((now - this.lastUpdate) / 1000, 0.1);
        this.lastUpdate = now;

        const follow = 1 - Math.exp(-PARALLAX_FOLLOW * dt);
        this.parallax.x += ((parallaxActive ? this.pointer.x : 0) - this.parallax.x) * follow;
        this.parallax.y += ((parallaxActive ? this.pointer.y : 0) - this.parallax.y) * follow;
        this.applyParallax(this.milkyWay, PARALLAX_MILKY_WAY);
        this.applyParallax(this.stars, PARALLAX_STARS);

        if (this.starMaterial) {
            this.starMaterial.uniforms.uPixelRatio.value = Math.min(window.devicePixelRatio, 2);
            // Wall-clock time keeps the pulse rate independent of the display refresh rate
            this.starMaterial.uniforms.uTime.value = performance.now() / 1000;
        }
    }

    /** Turns a layer opposite to the mouse, about the screen axes */
    applyParallax(layer: any, maxDegrees: number) {
        if (!layer) return;
        const amount = maxDegrees * Math.PI / 180;
        layer.rotation.set(this.parallax.y * amount, this.parallax.x * amount, 0, 'YXZ');
        layer.quaternion.multiply(this.orientation);
    }

    /**
     * Set starfield visibility
     */
    setVisible(visible) {
        this.sky.visible = visible;
    }

    /**
     * Get starfield mesh
     */
    getStars() {
        return this.stars;
    }

    /**
     * Destroy starfield
     */
    destroy() {
        window.removeEventListener('pointermove', this.onPointerMove);
        this.scene.remove(this.sky);
        if (this.milkyWay) {
            this.milkyWay.geometry.dispose();
            this.milkyWay.material.uniforms.uMap.value.dispose();
            this.milkyWay.material.dispose();
        }
        if (this.stars) {
            this.stars.geometry.dispose();
            this.starMaterial.dispose();
        }
        this.milkyWay = null;
        this.stars = null;
        this.starMaterial = null;
    }
}
